<refentry id="{@id}">
  <refnamediv>
    <refname>Geosearch Connector</refname>
    <refpurpose>
      The Geosearch connector is used to handle the communication between the geosearch and 
      other papaya modules.
    </refpurpose>
  </refnamediv>
  <refsynopsisdiv>
    <author>
      papaya Software GmbH
      <authorblurb>
        {@link mailto:info@papaya-cms.com papaya Software GmbH}
      </authorblurb>
    </author>
  </refsynopsisdiv>
  {@toc}
  <refsect1 id="{@id geosearch}">
    <title>Introduction</title>
    <para>
      The Geosearch connector is used to handle the communication between the geosearch and 
      other papaya modules.
    </para>
  </refsect1>
</refentry>